### ISSUE TITLE
How to build to docs methods of class and private members

### ISSUE THREAD

**Issue by unclechu** [75lb/gulp-jsdoc-to-markdown#1]
How I can build to MD file members of class and private members too?

**Comment by 75lb** [comment]
hey @unclechu .. i packaged up a pre-release version for you to play with.. 

install it
`$ npm install -g jsdoc-to-markdown@next`

then try it for yourself, for example: 
`$ jsdoc2md get_val/get_val.js`

take a look at the new options:
`$ jsdoc2md --help`

i don't have any issues with the `--private` option in this build, so i will close this issue.. let me know how it goes!
